import{a as q,S as v,i}from"./assets/vendor-BK_rxH-O.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&l(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function l(e){if(e.ep)return;e.ep=!0;const t=a(e);fetch(e.href,t)}})();const P="51799321-d2cea60cf5d9bf8518679ab71",B="https://pixabay.com/api/",$=15;async function m(r,o=1){try{return(await q.get(B,{params:{key:P,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:$,page:o}})).data}catch(a){throw console.error("Request error to Pixabay API:",a),a}}const y=document.querySelector(".gallery"),h=document.querySelector(".loader"),g=document.querySelector(".load-more"),M=new v(".gallery a",{captionsData:"alt",captionDelay:250});function p(r){const o=r.map(({webformatURL:a,largeImageURL:l,tags:e,likes:t,views:n,comments:w,downloads:S})=>`
      <li class="gallery-item">
        <a href="${l}">
          <img src="${a}" alt="${e}" loading="lazy" />
        </a>
        <div class="info">
          <p><b>Likes:</b> ${t}</p>
          <p><b>Views:</b> ${n}</p>
          <p><b>Comments:</b> ${w}</p>
          <p><b>Downloads:</b> ${S}</p>
        </div>
      </li>
    `).join("");y.insertAdjacentHTML("beforeend",o),M.refresh()}function O(){y.innerHTML=""}function b(){h.classList.remove("hidden")}function c(){h.classList.add("hidden")}function L(){g.classList.remove("hidden")}function u(){g.classList.add("hidden")}const x=document.querySelector(".form"),C=document.querySelector(".load-more");let d="",s=1,f=0;x.addEventListener("submit",async r=>{if(r.preventDefault(),d=r.target.searchQuery.value.trim(),!d){i.error({message:"Please enter a search query!"});return}s=1,O(),u(),b();try{const o=await m(d,s);if(f=o.totalHits,o.hits.length===0){i.info({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!",position:"center",backgroundColor:"#ef4040"}),c();return}p(o.hits),c(),f>s*15&&L()}catch{i.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"}),c()}});C.addEventListener("click",async()=>{s+=1,b(),u();try{const r=await m(d,s);p(r.hits),c(),E(),s*15>=f?(u(),i.info({message:"We're sorry, but you've reached the end of search results."})):L()}catch{i.error({message:"Something went wrong. Try again later."}),c()}});function E(){const{height:r}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
