import{a as v,S as P,i as s}from"./assets/vendor-BK_rxH-O.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&l(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function l(e){if(e.ep)return;e.ep=!0;const t=a(e);fetch(e.href,t)}})();const C="51799321-d2cea60cf5d9bf8518679ab71",R="https://pixabay.com/api/",g=15;async function h(r,o=1){try{return(await v.get(R,{params:{key:C,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:g,page:o}})).data}catch(a){throw console.error("Request error to Pixabay API:",a),a}}const p=document.querySelector(".gallery"),m=document.querySelector(".loader"),y=document.querySelector(".load-more"),B=new P(".gallery a",{captionsData:"alt",captionDelay:250});function b(r){const o=r.map(({webformatURL:a,largeImageURL:l,tags:e,likes:t,views:n,comments:S,downloads:q})=>`
      <li class="gallery-item">
        <a href="${l}">
          <img src="${a}" alt="${e}" loading="lazy" />
        </a>
        <div class="info">
          <p><b>Likes:</b> ${t}</p>
          <p><b>Views:</b> ${n}</p>
          <p><b>Comments:</b> ${S}</p>
          <p><b>Downloads:</b> ${q}</p>
        </div>
      </li>
    `).join("");p.insertAdjacentHTML("beforeend",o),B.refresh()}function $(){p.innerHTML=""}function L(){m.classList.remove("hidden")}function c(){m.classList.add("hidden")}function w(){y.classList.remove("hidden")}function u(){y.classList.add("hidden")}const E=document.querySelector(".form"),M=document.querySelector(".load-more");let d="",i=1,f=0;E.addEventListener("submit",async r=>{if(r.preventDefault(),d=r.target.searchQuery.value.trim(),!d){s.error({title:"Error",message:"Please enter a search query!",position:"topRight",backgroundColor:"#ef4040"});return}i=1,$(),u(),L();try{const o=await h(d,i);if(f=o.totalHits,o.hits.length===0){s.error({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",backgroundColor:"#ef4040"}),c();return}b(o.hits),c(),f>i*g?w():s.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight",backgroundColor:"#ef4040"})}catch{s.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight",backgroundColor:"#ef4040"}),c()}});M.addEventListener("click",async()=>{i+=1,L(),u();try{const r=await h(d,i);b(r.hits),c(),O(),i*g>=f?(u(),s.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight",backgroundColor:"#ef4040"})):w()}catch{s.error({title:"Error",message:"Something went wrong. Try again later.",position:"topRight",backgroundColor:"#ef4040"}),c()}});function O(){const{height:r}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
